[package]
name = "mat-mul-rs"
version = "0.1.0"
authors = ["Sachandhan Ganesh <sachan.ganesh@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "stitch-q",
]

[dependencies]
anyhow = "1.0.31"
async-std = "1.6.2"
crossbeam-channel = "0.4.2"
env_logger = "0.7"
log = "0.4"
uuid = { version = "0.8.1", features = ["serde", "v4"] }

stitch-q = { path = "stitch-q" }
