[package]
name = "seam-rs"
version = "0.0.1"
authors = ["Sachandhan Ganesh <sachan.ganesh@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "seam-channel",
    "seam-channel/examples/*",
    "seam-disruptor",
]

[dependencies]
seam-channel = { path = "seam-channel" }
seam-disruptor = { path = "seam-disruptor" }
