[package]
name = "stitch-rs"
version = "0.1.0"
authors = ["Sachandhan Ganesh <sachan.ganesh@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "stitch-channel",
]

[dependencies]
anyhow = "1.0.31"
async-channel = "1.4.0"
async-std = { version = "1.6.2", features = ["attributes"] }
env_logger = "0.7"
log = "0.4"
uuid = { version = "0.8.1", features = ["serde", "v4"] }

stitch-channel = { path = "stitch-channel" }
