[package]
name = "mat-mul-rs"
version = "0.1.0"
authors = ["Sachandhan Ganesh <sachan.ganesh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.4.2"
tokio = { version = "0.2.21", features = ["macros", "tcp"] }
serde = "1.0.112"
bincode = "1.2.1"