[package]
name = "mat-mul-rs"
version = "0.1.0"
authors = ["Sachandhan Ganesh <sachan.ganesh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.31"
async-bincode = "0.5.1"
async-std = "1.6.2"
bincode = "1.2.1"
crossbeam-channel = "0.4.2"
futures-core = "0.3.5"
mio = { version = "0.7.0", features = ["os-poll", "tcp"] }
serde = "1.0.112"
